import type { Metadata } from "next";
import "./globals.css";
import MaxWidthWrapper from "@/components/MaxWidthWrapper";
import Header from "@/components/Header";
import { cookies } from "next/headers";
import ThemeProvider from "@/components/ThemeProvider";

export const metadata: Metadata = {
  title: "Character Counter",
  description: "Generated by FrontEnd Mentor",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const savedTheme = (await cookies()).get("color-theme");
  const theme = savedTheme?.value || "light";
  return (
    <html data-theme={theme} lang="en">
      <body className="font-sans bg-[url(/assets/images/bg-light-theme.png)] dark:bg-[url(/assets/images/bg-dark-theme.png)] px-4 md:px-8">
        <MaxWidthWrapper>
          <ThemeProvider initialTheme={theme}>
            <Header />
            {children}
          </ThemeProvider>
        </MaxWidthWrapper>
      </body>
    </html>
  );
}
